version: '3'
networks:
  mysql-phpmyadmin:
    name: mysql-phpmyadmin
    # use the bridge driver
    driver: bridge

services:
  grib:
    build:
      context: .
      dockerfile: build/package/grib/Dockerfile
      args:
        IMAGE_NAME: ${GO_IMAGE}
        APP_NAME: ${APP_NAME}
        SERVICE: grib
        PORT: ${API_PORT}
    env_file:
      - ./.env
    volumes:
      - ./:/${APP_NAME}
    ports:
      - ${API_PORT}:${API_PORT}
    links:
      - ${DB_HOST}:${DB_HOST}
  db:
    image: ${DB_IMAGE}
    platform: "linux/amd64"
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: "linux/amd64"
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata:
